#!/bin/bash
: ${PROJ_ID:="EnergyApps"}

: ${QUEUE:="debug"} # debug, debug-scaling, prod https://docs.alcf.anl.gov/running-jobs/job-and-queue-scheduling/
#: ${NEKRS_HOME:="$HOME/.local/nekrs_bramesh"}
: ${NEKRS_HOME:="$HOME/.local/nekrs-ml-bsc"}
: ${NEKRS_CACHE_BCAST:=1}
: ${NEKRS_SKIP_BUILD_ONLY:=0}

if [ $# -ne 3 ]; then
  echo "usage: [PROJ_ID] [QUEUE] $0 <casename> <number of compute nodes> <hh:mm:ss>"
  exit 0
fi

if [ -z "$PROJ_ID" ]; then
  echo "ERROR: PROJ_ID is empty"
  exit 1
fi

if [ -z "$QUEUE" ]; then
  echo "ERROR: QUEUE is empty"
  exit 1
fi

bin=${NEKRS_HOME}/bin/nekrs
case=$1
nodes=$2
gpu_per_node=4
cores_per_numa=8
let nn=$nodes*$gpu_per_node
let ntasks=nn
time=$3

backend=CUDA
NEKRS_GPU_MPI=1

if [ ! -f $bin ]; then
  echo "Cannot find" $bin
  exit 1
fi

if [ ! -f $case.par ]; then
  echo "Cannot find" $case.par
  exit 1
fi

if [ ! -f $case.udf ]; then
  echo "Cannot find" $case.udf
  exit 1
fi

if [ ! -f $case.re2 ]; then
  echo "Cannot find" $case.re2
  exit 1
fi

striping_unit=16777216
max_striping_factor=128
let striping_factor=$nodes/2
if [ $striping_factor -gt $max_striping_factor ]; then
  striping_factor=$max_striping_factor
fi
if [ $striping_factor -lt 1 ]; then
  striping_factor=1
fi

MPICH_MPIIO_HINTS="*:striping_unit=${striping_unit}:striping_factor=${striping_factor}:romio_cb_write=enable:romio_ds_write=disable:romio_no_indep_rw=true"

# sbatch
SFILE=s.bin
echo "#!/bin/bash" > $SFILE
echo "#PBS -A $PROJ_ID" >>$SFILE
echo "#PBS -N nekRS_$case" >>$SFILE
echo "#PBS -q $QUEUE" >>$SFILE
echo "#PBS -l walltime=$time" >>$SFILE
echo "#PBS -l filesystems=home:eagle:grand" >>$SFILE
echo "#PBS -l select=$nodes:system=polaris" >>$SFILE
echo "#PBS -l place=scatter" >>$SFILE
echo "#PBS -k doe" >>$SFILE #write directly to the destination, doe=direct, output, error
#echo "#PBS -j eo" >>$SFILE  #oe=merge stdout/stderr to stdout
echo "#PBS -o out.o" >>$SFILE  #output
echo "#PBS -e error.e" >>$SFILE  #output


# job to “run” from your submission directory
echo "cd \$PBS_O_WORKDIR" >> $SFILE
echo "module restore" >>$SFILE
echo "module use /soft/modulefiles" >>$SFILE
echo "module load PrgEnv-gnu" >>$SFILE
echo "module load nvhpc-mixed/23.9" >>$SFILE
echo "module load craype-accel-nvidia80" >>$SFILE
#####echo "module unload nvhpc-mixed/23.9" >>$SFILE
echo "module load cudatoolkit-standalone/12.4.0" >>$SFILE
echo "module load craype-x86-milan" >>$SFILE
echo "module load spack-pe-base cmake" >>$SFILE
###echo "module unload cray-libsci" >>$SFILE

echo "module use /soft/modulefiles" >>$SFILE
echo "module load conda/2024-04-29" >>$SFILE
echo "conda activate base" >>$SFILE
echo "source /home/kumarv/install_nrsml/smartnekrs-env/bin/activate" >>$SFILE

echo "export CRAY_ACCEL_TARGET=nvidia80" >>$SFILE
echo "export NEKRS_HOME=/home/kumarv/.local/nekrs-ml-bsc" >>$SFILE
echo "export PATH=$NEKRS_HOME/bin:$PATH" >>$SFILE
echo "export TORCH_PATH=$( python -c 'import torch; print(torch.__path__[0])' )" >>$SFILE
echo "export LD_LIBRARY_PATH=$TORCH_PATH/lib:$LD_LIBRARY_PATH" >>$SFILE
echo "export LD_LIBRARY_PATH=/home/kumarv/install_nrsml/SmartRedis/install/lib:$LD_LIBRARY_PATH" >>$SFILE

echo "module list" >>$SFILE

echo "nvidia-smi" >> $SFILE
echo "ulimit -s unlimited " >>$SFILE

echo "export NEKRS_HOME=$NEKRS_HOME" >>$SFILE
echo "export NEKRS_GPU_MPI=$NEKRS_GPU_MPI" >>$SFILE

echo "export MPICH_MPIIO_HINTS=$MPICH_MPIIO_HINTS" >>$SFILE
echo "export MPICH_MPIIO_STATS=1" >>$SFILE

echo "export NEKRS_CACHE_BCAST=$NEKRS_CACHE_BCAST" >>$SFILE
echo "export NEKRS_LOCAL_TMP_DIR=/local/scratch" >>$SFILE

echo "export MPICH_GPU_SUPPORT_ENABLED=1" >> $SFILE
echo "export MPICH_OFI_NIC_POLICY=NUMA" >> $SFILE
#echo "export LD_PRELOAD=/opt/cray/pe/gcc/12.2.0/snos/lib64/libstdc++.so.6" >> $SFILE

# https://github.com/Nek5000/Nek5000/issues/759
#echo "export FI_OFI_RXM_RX_SIZE=32768" >> $SFILE # >=lelt, large mpi-messsage for restart
echo "export FI_OFI_RXM_RX_SIZE=65536" >> $SFILE # >=lelt, large mpi-messsage for restart

echo "export FI_CXI_RX_MATCH_MODE=hybrid" >> $SFILE


if [ $NEKRS_SKIP_BUILD_ONLY -eq 0 ]; then
echo "mpiexec -n 1 $bin --setup ${case} --backend ${backend} --device-id 0 --build-only $nn" >>$SFILE
fi

CMD=.lhelper
echo "#!/bin/bash" >$CMD
echo "gpu_id=\$((${gpu_per_node} - 1 - \${PMI_LOCAL_RANK} % ${gpu_per_node}))" >>$CMD
echo "export CUDA_VISIBLE_DEVICES=\$gpu_id" >>$CMD
echo "$bin --setup ${case} --backend ${backend} --device-id 0" >>$CMD
chmod 755 $CMD

echo "mpiexec -n $nn -ppn $gpu_per_node -d $cores_per_numa --cpu-bind depth ./$CMD" >>$SFILE

qsub -q $QUEUE $SFILE

# clean-up
#rm -rf $SFILE $ROMIO_HINTS .lhelper
